sudo: required

language: php

services:
  - docker

before_install:
- docker-compose up -d --build
- docker-compose ps
- docker-compose logs

script:
- docker-compose exec laravel-seeder code-coverage.sh